import XCTest
import CHDF5
@testable import SleapIO
@testable import SleapHDF5
import SleapVideo

/// S01-S03, S06-S07: SLP reader tests.
///
/// These tests require .slp fixture files generated by the Python script.
/// Tests will skip gracefully if fixtures are not available.
final class SLPReaderTests: XCTestCase {

    // MARK: - Fixture helpers

    private func fixtureURL(_ name: String) -> URL? {
        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // SleapHDF5Tests/
            .deletingLastPathComponent()  // Tests/
            .deletingLastPathComponent()  // package root
        let url = packageRoot.appendingPathComponent("Tests/Fixtures/\(name)")
        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }

    private func requireFixture(_ name: String, file: StaticString = #file, line: UInt = #line) throws -> URL {
        guard let url = fixtureURL(name) else {
            throw XCTSkip("Fixture '\(name)' not found — generate fixtures first")
        }
        return url
    }

    private func tempURL(extension ext: String = "slp") -> URL {
        FileManager.default.temporaryDirectory
            .appendingPathComponent("sleap_reader_\(UUID().uuidString).\(ext)")
    }

    private func makeSparseVideoIDFixture() throws -> URL {
        let url = tempURL()

        let file = try HDF5File.create(path: url.path)
        let metadata = try file.createGroup(name: "metadata")
        try metadata.writeFloatAttribute(name: "format_id", value: 1.5)
        try metadata.writeStringAttribute(
            name: "json",
            value: #"{"nodes":[],"provenance":{},"skeletons":[]}"#
        )
        try file.writeVLenStringDataset(
            name: "videos_json",
            strings: [
                #"{"id":10,"backend":{"filename":"video_a.mp4","type":"media"}}"#,
                #"{"id":20,"backend":{"filename":"video_b.mp4","type":"media"}}"#,
            ]
        )

        let compType = try HDF5Datatype.createCompound(size: 36)
        try compType.insertField(name: "frame_id", offset: 0, type: shim_H5T_NATIVE_UINT64())
        try compType.insertField(name: "video", offset: 8, type: shim_H5T_NATIVE_UINT32())
        try compType.insertField(name: "frame_idx", offset: 12, type: shim_H5T_NATIVE_UINT64())
        try compType.insertField(name: "instance_id_start", offset: 20, type: shim_H5T_NATIVE_UINT64())
        try compType.insertField(name: "instance_id_end", offset: 28, type: shim_H5T_NATIVE_UINT64())

        let space = try HDF5Dataspace.create(dims: [2])
        let frames = try file.createDataset(name: "frames", type: compType, space: space)

        var buffer = Data(count: 2 * 36)
        buffer.withUnsafeMutableBytes { ptr in
            let base = ptr.baseAddress!

            base.storeBytes(of: UInt64(0), toByteOffset: 0, as: UInt64.self)
            base.storeBytes(of: UInt32(10), toByteOffset: 8, as: UInt32.self)
            base.storeBytes(of: UInt64(3), toByteOffset: 12, as: UInt64.self)
            base.storeBytes(of: UInt64(0), toByteOffset: 20, as: UInt64.self)
            base.storeBytes(of: UInt64(0), toByteOffset: 28, as: UInt64.self)

            let second = base + 36
            second.storeBytes(of: UInt64(1), toByteOffset: 0, as: UInt64.self)
            second.storeBytes(of: UInt32(20), toByteOffset: 8, as: UInt32.self)
            second.storeBytes(of: UInt64(8), toByteOffset: 12, as: UInt64.self)
            second.storeBytes(of: UInt64(0), toByteOffset: 20, as: UInt64.self)
            second.storeBytes(of: UInt64(0), toByteOffset: 28, as: UInt64.self)
        }
        try buffer.withUnsafeBytes { ptr in
            try frames.writeRaw(ptr.baseAddress!, memType: compType.id)
        }

        return url
    }

    // MARK: - S01: Read .slp v1.5

    func testS01_readSparseV15_objectGraphReconstructed() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // Videos
        XCTAssertGreaterThan(labels.videos.count, 0, "Should have at least one video")

        // Skeletons
        XCTAssertGreaterThan(labels.skeletons.count, 0, "Should have at least one skeleton")
        let skeleton = labels.skeletons[0]
        XCTAssertGreaterThan(skeleton.nodes.count, 0, "Skeleton should have nodes")

        // Labeled frames
        XCTAssertGreaterThan(labels.count, 0, "Should have labeled frames")

        // User instances (sparse fixture has user instances only)
        let frame = labels[0]
        XCTAssertGreaterThan(frame.instances.count, 0, "Frame should have instances")

        // Verify frame has valid data
        XCTAssertGreaterThanOrEqual(frame.frameIndex, 0)
        XCTAssertTrue(labels.videos.contains(where: { $0 === frame.video }))
    }

    func testS01_readSparseV15_multipleVideos() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // The sparse fixture should have multiple videos
        XCTAssertGreaterThanOrEqual(
            labels.videos.count, 2,
            "Sparse fixture should have multiple videos"
        )

        // Each video should be a distinct object
        for i in 0..<labels.videos.count {
            for j in (i + 1)..<labels.videos.count {
                XCTAssertFalse(
                    labels.videos[i] === labels.videos[j],
                    "Each video should be a distinct object"
                )
            }
        }
    }

    func testS01_readDensePredictionsV15() async throws {
        let url = try requireFixture("dense_predictions_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // Should have both user and predicted instances
        XCTAssertGreaterThan(labels.count, 0)

        var foundUser = false
        var foundPredicted = false
        for i in 0..<min(labels.count, 20) {
            let frame = labels[i]
            if frame.hasUserInstances { foundUser = true }
            if !frame.predictedInstances.isEmpty { foundPredicted = true }
        }

        XCTAssertTrue(foundPredicted, "Dense predictions fixture should have predicted instances")

        // Should have tracks
        XCTAssertGreaterThan(labels.tracks.count, 0, "Should have tracks")
    }

    func testS01_readV15_skeletonSharedAcrossInstances() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        let skeleton = labels.skeletons[0]

        // All instances using this skeleton should reference the same object
        for i in 0..<min(labels.count, 10) {
            for inst in labels[i].instances {
                if inst.skeleton.name == skeleton.name {
                    XCTAssertTrue(
                        inst.skeleton === skeleton,
                        "Instance skeleton must be identity-equal to the Labels skeleton"
                    )
                }
            }
        }
    }

    func testS01_readV15_pointsHaveValidCoordinates() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        let frame = labels[0]
        guard let inst = frame.instances.first else {
            throw XCTSkip("No instances in first frame")
        }

        // Points count should match skeleton node count
        XCTAssertEqual(
            inst.points.count,
            inst.skeleton.nodes.count,
            "Points count must match skeleton node count"
        )

        // At least some points should have non-NaN coordinates
        var hasVisiblePoint = false
        for j in 0..<inst.points.count {
            if inst.points.visibility[j] {
                XCTAssertFalse(inst.points[j].x.isNaN)
                XCTAssertFalse(inst.points[j].y.isNaN)
                hasVisiblePoint = true
            }
        }
        XCTAssertTrue(hasVisiblePoint, "Instance should have at least one visible point")
    }

    func testS01_readV15_suggestionsLoaded() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // Suggestions may or may not be present in the fixture.
        // If they are, verify basic structure.
        for suggestion in labels.suggestions {
            XCTAssertGreaterThanOrEqual(suggestion.frameIndex, 0)
            XCTAssertTrue(
                labels.videos.contains(where: { $0 === suggestion.video }),
                "Suggestion video must reference a Labels video"
            )
        }
    }

    // MARK: - S02: Read legacy format behaviors

    func testS02_legacyV10_coordinateAdjusted() async throws {
        let url = try requireFixture("legacy_v1_0.slp")
        let labels = try await Labels.load(from: url)

        // Pre-1.1 files should have points adjusted by -0.5
        // We can't directly verify the adjustment without knowing the original values,
        // but we verify the file loads successfully and has valid data
        XCTAssertGreaterThan(labels.count, 0)

        let frame = labels[0]
        guard let inst = frame.instances.first else {
            throw XCTSkip("No instances in first frame")
        }

        // Points should be valid (the -0.5 adjustment means they can be negative,
        // but should still be finite)
        for j in 0..<inst.points.count where inst.points.visibility[j] {
            XCTAssertFalse(inst.points[j].x.isNaN, "Adjusted points should not be NaN")
            XCTAssertFalse(inst.points[j].y.isNaN)
            XCTAssertTrue(inst.points[j].x.isFinite)
            XCTAssertTrue(inst.points[j].y.isFinite)
        }
    }

    func testS02_legacyV11_missingTrackingScoreHandled() async throws {
        let url = try requireFixture("legacy_v1_1.slp")
        let labels = try await Labels.load(from: url)

        // Pre-1.2 files have 9-field instances (no tracking_score).
        // The file should load without failure.
        XCTAssertGreaterThan(labels.count, 0)

        // Instances should exist without error
        for i in 0..<min(labels.count, 5) {
            let frame = labels[i]
            for inst in frame.instances {
                // tracking_score should default to 0.0 or nil
                XCTAssertNotNil(inst)
            }
        }
    }

    func testS02_legacyV13_embeddedChannelOrderDefaultsBGR() async throws {
        let url = try requireFixture("legacy_v1_3.slp")
        let labels = try await Labels.load(from: url)

        // Pre-1.4 packaged files should default to BGR channel order.
        // We primarily verify the file loads without failure.
        XCTAssertGreaterThan(labels.count, 0)
    }

    // MARK: - S03: Sparse video ID remapping

    func testS03_sparseVideoIDsResolveCorrectly() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // All frames should have their video property pointing to a valid Video
        // in the labels.videos list
        for i in 0..<labels.count {
            let frame = labels[i]
            let videoInList = labels.videos.contains(where: { $0 === frame.video })
            XCTAssertTrue(
                videoInList,
                "Frame \(i)'s video must be in the labels.videos list"
            )
        }
    }

    func testS03_multiVideoFramesResolveToCorrectVideo() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        guard labels.videos.count >= 2 else {
            throw XCTSkip("Need at least 2 videos for this test")
        }

        // Check that frames(for:) returns frames for distinct videos
        let framesV0 = labels.frames(for: labels.videos[0])
        let framesV1 = labels.frames(for: labels.videos[1])

        // Frames for different videos should not overlap
        for f in framesV0 {
            XCTAssertTrue(f.video === labels.videos[0])
        }
        for f in framesV1 {
            XCTAssertTrue(f.video === labels.videos[1])
        }

        // Total should account for all frames
        let totalPerVideo = framesV0.count + framesV1.count
        // May be <= labels.count if there are more than 2 videos
        XCTAssertGreaterThan(totalPerVideo, 0)
    }

    func testSparsePersistedVideoIDsResolveForLazyAndEagerLoads() async throws {
        let url = try makeSparseVideoIDFixture()
        defer { try? FileManager.default.removeItem(at: url) }

        let lazy = try await Labels.load(from: url)
        XCTAssertEqual(lazy.frames(for: lazy.videos[0]).map(\.frameIndex), [3])
        XCTAssertEqual(lazy.frames(for: lazy.videos[1]).map(\.frameIndex), [8])
        XCTAssertTrue(lazy[0].video === lazy.videos[0])
        XCTAssertTrue(lazy[1].video === lazy.videos[1])

        let eager = try await Labels.loadEager(from: url)
        XCTAssertEqual(eager.frames(for: eager.videos[0]).map(\.frameIndex), [3])
        XCTAssertEqual(eager.frames(for: eager.videos[1]).map(\.frameIndex), [8])
        XCTAssertTrue(eager[0].video === eager.videos[0])
        XCTAssertTrue(eager[1].video === eager.videos[1])
    }

    // MARK: - S06: Embedded frame support

    func testS06_packagedSlpLoadsEmbeddedFrames() async throws {
        let url = try requireFixture("packaged_frames_v1_5.pkg.slp")
        let labels = try await Labels.load(from: url)

        XCTAssertGreaterThan(labels.count, 0)
        XCTAssertGreaterThan(labels.videos.count, 0)

        // The video should be detected as embedded
        // (implementation-specific: filename might be "." or have embedded metadata)
    }

    func testS06_embeddedFrameNumbersMappingRespected() async throws {
        let url = try requireFixture("packaged_frames_v1_5.pkg.slp")
        let labels = try await Labels.load(from: url)

        // Sparse frame_numbers: labeled frames may reference non-contiguous source indices.
        // Verify frames have valid indices and data.
        for i in 0..<labels.count {
            let frame = labels[i]
            XCTAssertGreaterThanOrEqual(frame.frameIndex, 0)
            XCTAssertGreaterThan(frame.instances.count, 0)
        }
    }

    func testS06_embeddedVideoFrameAccessibleThroughVideoAPI() async throws {
        let url = try requireFixture("packaged_frames_v1_5.pkg.slp")
        let labels = try await Labels.load(from: url)

        var resolvedImage = false
        for i in 0..<labels.count {
            let frame = labels[i]
            do {
                let image = try await frame.video.frame(at: frame.frameIndex)
                XCTAssertGreaterThan(image.width, 0)
                XCTAssertGreaterThan(image.height, 0)
                resolvedImage = true
                break
            } catch {
                continue
            }
        }

        XCTAssertTrue(resolvedImage, "Expected at least one packaged frame to be retrievable through Video.frame(at:)")
    }

    func testS06_embeddedVideoCanReopenAfterClose() async throws {
        let url = try requireFixture("packaged_frames_v1_5.pkg.slp")
        let labels = try await Labels.load(from: url)

        var resolved: (video: Video, frameIndex: Int)?
        for i in 0..<labels.count {
            let frame = labels[i]
            do {
                _ = try await frame.video.frame(at: frame.frameIndex)
                resolved = (frame.video, frame.frameIndex)
                break
            } catch {
                continue
            }
        }

        guard let resolved else {
            XCTFail("Expected at least one packaged frame to be retrievable before reopen")
            return
        }

        resolved.video.close()
        try await resolved.video.open()

        let image = try await resolved.video.frame(at: resolved.frameIndex)
        XCTAssertGreaterThan(image.width, 0)
        XCTAssertGreaterThan(image.height, 0)
    }

    // MARK: - S07: from_predicted link resolution

    func testS07_fromPredictedLinksResolved() async throws {
        let url = try requireFixture("dense_predictions_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // Look for user instances that have from_predicted links
        var foundLink = false
        for i in 0..<min(labels.count, 50) {
            let frame = labels[i]
            for inst in frame.userInstances {
                if let pred = inst.fromPredicted {
                    foundLink = true
                    // The linked prediction should be identity-equal to a predicted instance
                    // already in the frame graph
                    XCTAssertTrue(pred is PredictedInstance)

                    // It should be findable in some frame's instances
                    var foundInGraph = false
                    for j in 0..<min(labels.count, 50) {
                        for predInst in labels[j].predictedInstances {
                            if predInst === pred {
                                foundInGraph = true
                                break
                            }
                        }
                        if foundInGraph { break }
                    }
                    XCTAssertTrue(
                        foundInGraph,
                        "from_predicted reference should point to an instance in the frame graph"
                    )
                }
            }
        }
        // Note: not all fixtures will have from_predicted links; this is expected
        // If none found, the test still passes — it just doesn't verify the link
    }

    func testS07_missingFromPredictedProducesNil() async throws {
        let url = try requireFixture("sparse_v1_5.slp")
        let labels = try await Labels.load(from: url)

        // Sparse fixture has user instances only — from_predicted should be nil
        for i in 0..<min(labels.count, 10) {
            for inst in labels[i].userInstances {
                // Missing or sentinel from_predicted should produce nil, not crash
                // (nil is the expected default)
                _ = inst.fromPredicted  // Should not crash
            }
        }
    }

    // MARK: - Multiview support

    func testMultiviewSessionsLoaded() async throws {
        let url = try requireFixture("multiview_v1_5.slp")
        let labels = try await Labels.load(from: url)

        XCTAssertGreaterThan(labels.count, 0)
        // Multiview files should have sessions
        XCTAssertGreaterThan(
            labels.sessions.count, 0,
            "Multiview fixture should have recording sessions"
        )
    }

    // MARK: - ROI and mask support

    func testROIsAndMasksLoaded() async throws {
        let url = try requireFixture("roi_mask_v1_5.slp")
        let labels = try await Labels.load(from: url)

        XCTAssertGreaterThan(labels.count, 0)

        // Should have ROIs and/or masks
        let hasROIs = !labels.rois.isEmpty
        let hasMasks = !labels.masks.isEmpty
        XCTAssertTrue(
            hasROIs || hasMasks,
            "ROI/mask fixture should have ROIs or masks"
        )
    }

    // MARK: - Video.frameCount from SLP metadata

    func testDecodeVideo_withShape_setsFrameCountAndFrameSize() {
        let dict: [String: Any] = [
            "backend": [
                "filename": "video.mp4",
                "type": "media",
                "shape": [100, 480, 640, 3],
            ] as [String: Any]
        ]

        let video = SLPVideoTable.decodeVideo(from: dict)

        XCTAssertEqual(video.frameCount, 100)
        XCTAssertNotNil(video.frameSize)
        XCTAssertEqual(video.frameSize?.height, 480)
        XCTAssertEqual(video.frameSize?.width, 640)
        XCTAssertEqual(video.frameSize?.channels, 3)
    }

    func testDecodeVideo_withoutShape_leavesFrameCountAndFrameSizeNil() {
        let dict: [String: Any] = [
            "backend": [
                "filename": "video.mp4",
                "type": "media",
            ] as [String: Any]
        ]

        let video = SLPVideoTable.decodeVideo(from: dict)

        XCTAssertNil(video.frameCount)
        XCTAssertNil(video.frameSize)
    }

    // MARK: - Video relocation decode

    func testDecodeVideo_legacySLP_noRelocation() {
        let dict: [String: Any] = [
            "backend": [
                "filename": "/data/video.mp4",
                "type": "media",
            ] as [String: Any]
        ]

        let video = SLPVideoTable.decodeVideo(from: dict)

        XCTAssertEqual(video.originalFilename, "/data/video.mp4")
        XCTAssertNil(video.persistedFilename)
        XCTAssertEqual(video.filename, "/data/video.mp4")
    }

    func testDecodeVideo_relocatedSLP_restoresProvenance() {
        let dict: [String: Any] = [
            "backend": [
                "filename": "/ipad/Documents/video.mp4",
                "type": "media",
                "original_filename": "/linux/train/video.mp4",
            ] as [String: Any]
        ]

        let video = SLPVideoTable.decodeVideo(from: dict)

        XCTAssertEqual(video.originalFilename, "/linux/train/video.mp4")
        XCTAssertEqual(video.persistedFilename, "/ipad/Documents/video.mp4")
        XCTAssertEqual(video.filename, "/ipad/Documents/video.mp4")
    }

    func testDecodeVideo_roundTrip_shapeWrittenAndPreserved() async throws {
        let skeleton = Skeleton(name: "fly", nodes: [Node(name: "head")])
        let video = Video(filename: "shape_test.mp4")
        video.frameCount = 200
        video.frameSize = (height: 720, width: 1280, channels: 3)

        let frame = LabeledFrame(
            video: video,
            frameIndex: 0,
            instances: [Instance(skeleton: skeleton)]
        )
        let labels = Labels(
            frameStore: EagerFrameStore(frames: [frame]),
            videos: [video],
            skeletons: [skeleton],
            tracks: []
        )

        let outputURL = tempURL()
        defer { try? FileManager.default.removeItem(at: outputURL) }

        try await labels.save(to: outputURL)

        let reloaded = try await Labels.loadEager(from: outputURL)

        XCTAssertEqual(reloaded.videos.count, 1)
        let reloadedVideo = reloaded.videos[0]
        XCTAssertEqual(reloadedVideo.frameCount, 200)
        XCTAssertNotNil(reloadedVideo.frameSize)
        XCTAssertEqual(reloadedVideo.frameSize?.height, 720)
        XCTAssertEqual(reloadedVideo.frameSize?.width, 1280)
        XCTAssertEqual(reloadedVideo.frameSize?.channels, 3)
    }
}
